name: Generate WARP Config

on:
  schedule:
    - cron: '0 */12 * * *' 
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    env:
      ENDPOINTS_URL: https://example.com/endpoints.json
      OUTPUT_FILE: result.json

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Download, Process and Generate result.json
        run: python generate.py

      - name: Commit result.json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add result.json
          git commit -m "Generated result.json from URL" || echo "No changes to commit"
          git push
